title: POPDG: Popular 3D Dance Generation with PopDanceSet
description: >-
  Zhenye Luo, Min Ren, Xuecai Hu, Yongzhen Huang, Li Yao
# baseurl: ""
# url: "https://luke-luo1.github.io/POPDG"

# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Other configurations
markdown: kramdown
highlighter: rouge
show_downloads: true

# title: POPDG
# description: >-
#   A brief description of the POPDG project.
# show_downloads: true
# remote_theme: pages-themes/cayman@v0.2.0

