title: "POPDG: Popular 3D Dance Generation with PopDanceSet"
description: >
  Zhenye Luo, Min Ren, Xuecai Hu, Yongzhen Huang, Li Yao<br>
  Beijing Normal University

# baseurl: ""
# url: "https://luke-luo1.github.io/POPDG"

# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Other configurations
markdown: kramdown
highlighter: rouge
show_downloads: true



