title: POPDG
description: >-
  A brief description of the POPDG project.
baseurl: ""
url: "https://luke-luo1.github.io/POPDG"

theme: jekyll-theme-cayman

# Other configurations
markdown: kramdown
highlighter: rouge
