title: Your Project Title
description: >- # this means to ignore newlines until "baseurl:"
  A brief description of your project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luke-luo1.github.io/POPDG/" # the base hostname & protocol for your site

theme: Cayman

# Other configurations
markdown: kramdown
highlighter: rouge
